### ISSUE TITLE
where can i find Animation and Skinning demo

### ISSUE THREAD

**Issue by Lucklycat** [NVlabs/nvdiffrast#103]
hi, i am read the papaer--Appearance-Driven Automatic 3D Model Simplification, think it's great.  But in the demo,i can not find the Animation and Skinning demo, where can i find it ?  I want to study how to do it.
please help !
thanks

**Comment by s-laine** [comment]
The repo for that paper is at [https://github.com/NVlabs/nvdiffmodeling](https://github.com/NVlabs/nvdiffmodeling)

**Comment by Lucklycat** [comment]
hi，i see the repo. but in the repo demos,not have the Animation and Skinning demo
