### ISSUE TITLE
Points rasterizer

### ISSUE THREAD

**Issue by gaobodaxinwen** [NVlabs/nvdiffrast#109]
Thanks for sharing this great work! It seems that egl is used for rasterization and meshes are required as input. I wonder if it would be possible to rasterize point clouds using nvdiffrast like https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/render_colored_points.ipynb.

**Comment by s-laine** [comment]
Nvdiffrast doesn't support rasterizing primitives other than triangle meshes. It would be possible to simulate point-based rendering by rasterizing multiple layers of camera-oriented billboards (one per point) using depth peeling, and blending the results together heuristically like the point-based renderers do. The performance might not be great, though.

**Comment by gaobodaxinwen** [comment]
Thanks for your advice! I will try it as you say.
