### ISSUE TITLE
Error when trying to use other gpus rather than gpu 0

### ISSUE THREAD

**Issue by hiyyg** [NVlabs/nvdiffrast#11]
Hello, I try to run `nvdiffrast` on other gpus rather than gpu 0 by running:
`CUDA_VISIBLE_DEVICES=1 python samples/torch/triangle.py`
However, I got this error:
```
Traceback (most recent call last):
  File "samples/torch/triangle.py", line 26, in <module>
    rast, _ = dr.rasterize(glctx, pos, tri, resolution=[256, 256])
  File "nvdiffrast/nvdiffrast/torch/ops.py", line 227, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db)
  File "nvdiffrast/nvdiffrast/torch/ops.py", line 169, in forward
    out, out_db = _get_plugin().rasterize_fwd(glctx.cpp_wrapper, pos, tri, resolution, ranges)
RuntimeError: CUDA error: invalid device ordinal
```
How can I solve this problem?

**Comment by hiyyg** [comment]
solved

**Comment by s-laine** [comment]
Hi hiyyg and sorry for the delayed reply. Proper multi-GPU support is currently missing from the library but I'm going to start working on it soon. If it's not too much trouble, I'd like to hear what your solution was - my current plan for Linux is to use the `eglGetPlatformDisplayEXT()` extension. Is this perhaps what you did, or did you find some other solution?

**Comment by hiyyg** [comment]
Exactly.

**Comment by Dengzhi-USTC** [comment]
Hi, I still have this problem when i use the eglGetPlatformDisplayEXT()? can you give some advices?
Thank you very much.

My codes:
def create_initialized_headless_egl_display():
    device = EGL.eglQueryDevicesEXT()[1]
    display = EGL.eglGetPlatformDisplayEXT(
        EGL.EGL_PLATFORM_DEVICE_EXT, device, None)
    if display != EGL.EGL_NO_DISPLAY and EGL.eglGetError() == EGL.EGL_SUCCESS:
        try:
            initialized = EGL.eglInitialize(display, None, None)
        except EGL.error.GLError:
            pass 
        else:
            if initialized == EGL.EGL_TRUE and EGL.eglGetError() == EGL.EGL_SUCCESS:
                return display
    return EGL.EGL_NO_DISPLAY

create_initialized_headless_egl_display()
self.glctx = dr.RasterizeCudaContext() 
dr.RasterizeCudaContext() also create the buffer in the gpu:0.
