### ISSUE TITLE
Backpropagation of nvdiffrast.torch.rasterize

### ISSUE THREAD

**Issue by jiaxiangshang** [NVlabs/nvdiffrast#112]
Dear groupers,

Thanks again for your great job

When I use the return of nvdiffrast.torch.rasterize (u, v, z/w, triangle_id), will triangle_id support backpropagation?

Best
Jiaxiang

**Comment by s-laine** [comment]
No, triangle_id is a discrete variable so there is no meaningful gradient.

If you're thinking of geometry gradients related to visibility/occlusion in general, those are obtained via the antialiasing op, as explained in the documentation.
