### ISSUE TITLE
How to render depth maps?

### ISSUE THREAD

**Issue by chinhsuanwu** [NVlabs/nvdiffrast#114]
I tried `rasterizaion()` and took the normalized depth `z/w` but doesn't seems to be a depth map but occlusion.
I wonder if it is possible to render depth maps with nvdiffrast.

Thanks in advance!

![test](https://user-images.githubusercontent.com/67839539/232415109-d1a6b3f9-9c6e-4f56-8ab3-5c9fdd99ea06.png)

**Comment by s-laine** [comment]
I suppose your projection matrix has a large far/near ratio, and thus all normalized depths are on a very small range. In an image like this, they then show up as an almost constant color. Try mapping the range of nonzero depth values to black-white, and you should see that the depth detail is actually in there.

Be aware that the rasterizer z/w channel does not propagate gradients. If you need gradients of the depth to propagate to vertex positions, you'll need to create an attribute tensor for vertex depths and interpolate that using the interpolation operation.

**Comment by chinhsuanwu** [comment]
Hi @s-laine 

Thank you so much. It works!

As for how to propagate gradients through an interpolated attribute tensor, are you inferring something like this?

https://github.com/NVlabs/nvdiffrec/blob/e7f2181b8a60eb8fedcdb4ad4d05bff3c0cf9bc1/render/render.py#L155

Thanks again for your useful response.
