### ISSUE TITLE
FAILED: nvdiffrast_plugin_gl.so 

### ISSUE THREAD

**Issue by rohitdhote111** [NVlabs/nvdiffrast#116]
FAILED: nvdiffrast_plugin_gl.so 
c++ common.o glutil.o rasterize_gl.o torch_bindings_gl.o torch_rasterize_gl.o -shared -lGL -lEGL -L/opt/conda/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/opt/conda/lib64 -lcudart -o nvdiffrast_plugin_gl.so
/usr/bin/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by s-laine** [comment]
Your Cuda toolkit installation appears to be incomplete. `cudart` is the Cuda runtime library.

**Comment by rohitdhote111** [comment]
@s-laine Hi, Thanks for the reply
I am using docker container pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel so cuda toolkit is already installed. I also checked it with nvcc --verion command. Let me know if I am missing something

**Comment by rohitdhote111** [comment]
solved in #115
