### ISSUE TITLE
how to render with multiple uv mappings

### ISSUE THREAD

**Issue by linzhenyuyuchen** [NVlabs/nvdiffrast#119]
Thank you for your great work!
I have implemented the nvdiffrast for my work, however i am puzzled about how to render an image with `nvdiffrast.torch.texture(tex, uv)` if there are multile uv mappings.
Hope your help, Thanks again !

**Comment by s-laine** [comment]
There is no builtin support for that. You'll have to either composite the final image from multiple renderings, or consolidate the textures into a single texture atlas and modify the uv mappings accordingly.

**Comment by linzhenyuyuchen** [comment]
Thank you for your help!
