### ISSUE TITLE
python to c++

### ISSUE THREAD

**Issue by chky1997** [NVlabs/nvdiffrast#124]
Hi, thank you first for your great framework. I'm working on my python project using nvdiffrast.torch.rasterize() and nvdiffrast.torch.interpolate() to render a mesh. For further use, I need to convert my python code to c++ code, but I'm not familiar with c++. Could you please tell me how to use the two python functions above in a c++ project? Thank you!

**Comment by s-laine** [comment]
The Python functions in `nvdiffrast/torch/ops.py` are simply wrappers that call the C++ functions in the extension plugin, so you shouldn't need anything from them &mdash; from C++ code, you can call the C++ functions directly instead. These functions handle the interfacing between PyTorch and the CUDA kernels that do the actual computation, so if you're planning on not using Torch/PyTorch either, you'll have to modify them to operate with whatever tensor abstraction you have.

**Comment by chky1997** [comment]
Thank you for your reply! Following your instruction, I found that rasterize.cu and interpolate.cu define some CUDA kernels for the actual computation. However, when I tried to use the kernels, many “undefined identifier“ and other errors occurred. How to solve this? Is there any head files should be added?
![image](https://github.com/NVlabs/nvdiffrast/assets/62194406/d6582bc7-f761-47c9-a6b3-ef43245f685d)
![image](https://github.com/NVlabs/nvdiffrast/assets/62194406/f41ba879-beb6-4063-aa7a-2d06d583f03a)
![image](https://github.com/NVlabs/nvdiffrast/assets/62194406/260c21d7-c58b-4d4d-885c-91bebc507e31)

By the way, I'd appreciate it if there is any c++ example or guide can be provided. My email is chky1997@163.com. Thank you very much for your help!

**Comment by s-laine** [comment]
This is not an issue with nvdiffrast anymore, and general Cuda/C++ programming is way outside the scope of this issue tracker. I suggest you look for beginner-friendly tutorials for Cuda and C++ programming &mdash; there are many available online.

Closing as out-of-scope.
