### ISSUE TITLE
nvdiffrast_plugin_gl.so

### ISSUE THREAD

**Issue by chxinyv** [NVlabs/nvdiffrast#130]
请问需要怎样才能获取nvdiffrast_plugin_gl.so文件？

**Comment by s-laine** [comment]
The extension library should be built and loaded automatically by PyTorch's extension build mechanism. If this doesn't work, your system is probably lacking some of the necessary libraries and/or tools. We suggest using the provided Dockerfile. Alternatively, you can inspect the Dockerfile and manually ensure your system has all the dependencies included therein.
