### ISSUE TITLE
Native CPP support

### ISSUE THREAD

**Issue by tperl-cg** [NVlabs/nvdiffrast#143]
Hi,
Can I build nvdiffrast to work with cpp and ceres optimizer?

**Comment by s-laine** [comment]
No, the code currently supports PyTorch/TensorFlow only. However, if you're willing to port nvdiffrast ops to support a different framework, all you need is a new set of C++ stubs that act as an interface to the Cuda kernels, similar to how the C++ code in `nvdiffrast/torch` interfaces between PyTorch and Cuda.

**Comment by tperl-cg** [comment]
Can It work with iOS metal? or on CPU?  how can I support this with the tool chain? can you give an example?

**Comment by s-laine** [comment]
No, it won't work without a Cuda-compatible GPU. All the important bits are implemented using Cuda.

**Comment by tperl-cg** [comment]
I am confused, it is written the it supports open-gl
