### ISSUE TITLE
When using nvdifast on multiple GPUs, lock file exists in build directory appears

### ISSUE THREAD

**Issue by Fjzd** [NVlabs/nvdiffrast#145]
When using nvdifast on multiple GPUs, lock file exists in build directory appears

**Comment by s-laine** [comment]
Duplicate of #67

**Comment by jpainam** [comment]
what file should I delete? `./cache/torch_extensions/nvdiffrast_plugin/lock'`, only the `lock` file or all the `nvdiffrast_plugin` extension?
