### ISSUE TITLE
wrong rasterize on A100

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [NVlabs/nvdiffrast#146]
![image](https://github.com/NVlabs/nvdiffrast/assets/30692249/98ef904e-43bc-4d30-b156-eae42efc6072)
There is a rasterize error on A100, but it performs correctly on other GPU. How to solve this problem?

**Comment by ZHANG-SHI-CHANG** [comment]
> This should be fixed in nvdiffrast v0.2.8 and later. The most recent GPU drivers for A100 also include a fix to this issue.
> 
> The solution is to update either nvdiffrast or the GPU drivers to the latest version.

Thank you for your reply! Do both of these conditions need to be met? Currently, nvdiffrats is already the latest version.

**Comment by s-laine** [comment]
Either condition alone should be sufficient, but apparently that is not the case. If you already have the latest nvdiffrast, I suppose there is a driver version that somehow defeats the bugfix in nvdiffrast. The most recent GPU driver (currently [535.129.03](https://www.nvidia.com/Download/driverResults.aspx/214066/en-us/)) should resolve the issue on a driver level.
