### ISSUE TITLE
VS Enterprise edition not detected

### ISSUE THREAD

**Issue by msqrt** [NVlabs/nvdiffrast#15]
The linker search in torch/ops.py ([here](https://github.com/NVlabs/nvdiffrast/blob/5a2d5d595ef94c63f186dc497c6223c866a33995/nvdiffrast/torch/ops.py#L31)) doesn't have `'Enterprise'` in the list of potential version names.

**Comment by s-laine** [comment]
Thanks @msqrt! Added this to the search paths.
