### ISSUE TITLE
bad reconstruction result compared to pytorch3d

### ISSUE THREAD

**Issue by lcc815** [NVlabs/nvdiffrast#150]
Hi, dear author

I reconstructed a scene by nvdiffrast and pytorch3d, but there are hugh gap between the finnal result (construction algrithm is as the same as cube demo.)
pytorch3d result:
![pytorch3d result](https://github.com/NVlabs/nvdiffrast/assets/97278927/2716ab2d-8370-4192-8d89-463ebecff270)
nvdiffrast result:
![nvrast result](https://github.com/NVlabs/nvdiffrast/assets/97278927/f701e528-ce32-4c1e-8b55-c1f3554d91b8)

I follow the sample to get the rendering function, just like follows:
```
def __call__(self, pos_ndc, pos_idx, vtx_col, resolution: tuple):
        rast_out, _ = dr.rasterize(self.glctx, pos_ndc, pos_idx, resolution=resolution)
        color, _    = dr.interpolate(vtx_col, rast_out, pos_idx)
        color       = dr.antialias(color, rast_out, pos_ndc, pos_idx)
        return color
```

Is there any way to improve the reconstruction quality? Or have I made any potential mistakes?

Thanks.

**Comment by lcc815** [comment]
if look at local, ti's the same.
pytorch3d:
![image](https://github.com/NVlabs/nvdiffrast/assets/97278927/42f9d95e-5ba9-47c8-9e46-8b10dbf39f41)

nvdiffrast:
![image](https://github.com/NVlabs/nvdiffrast/assets/97278927/fbb08c76-f1ac-4037-a5bf-c7b22edbc166)

one can see there are some strange things in the nvdiffrast.

**Comment by s-laine** [comment]
This looks similar to the problems in #105. I think it's undersampling, i.e., you're rasterizing the image in too low resolution or too wide crops for the geometry resolution, so that the individual triangles are always smaller than a pixel. The first thing to try would be lowering the model resolution or increasing the rendering resolution.

Are you trying to optimize both geometry and colors, or just the latter? If you're not optimizing geometry, using a texture map would probably work better than using vertex colors &mdash; there you can use texture filtering, whereas dense geometry will always alias in too low resolutions.

**Comment by lcc815** [comment]
I am just trying to optimize only colors, I will try using a texture map just like what you recommended. However, for directly optimizing the vertex colors, I don't think this unexpected results is caused by undersampling. because I have tried to increase image resolution(rasterizer resolution*2, followed by ave_pooling to keep output resolution unchanged), the problem persists.
And, if I overfit a single image, I got this result: there is strange white circle arc on the edge
![image](https://github.com/NVlabs/nvdiffrast/assets/97278927/9978d771-6403-4f33-90e3-89bcd29a4cfb)
correspondingly, the rendering image is also wrong I think
![image](https://github.com/NVlabs/nvdiffrast/assets/97278927/11cd4e46-b771-433e-b7fb-c2879cb74ab9)
In contrast, the result of pytorch3d looks like more reasonable:
![image](https://github.com/NVlabs/nvdiffrast/assets/97278927/5ea75142-6c3e-40af-b42d-265d0895e107)
![image](https://github.com/NVlabs/nvdiffrast/assets/97278927/9d6e41f3-e100-42d9-bba4-9ce49e7b31e5)
I think this issue can be easily reproduced.

**Comment by s-laine** [comment]
I think it's still aliasing one way or another, but at this kind of grazing angles there might be a precision problem with the barycentrics as well. Downsampling a rasterized image isn't quite as effective as solving these issues as you might thin

**Comment by s-laine** [comment]
Apologies, I apparently hit a keyboard shortcut that closed the issue. That was not the intent, so reopened.

**Comment by lcc815** [comment]
OK, got it, thanks for your reply.
One more question. Do you think using a texture map will help solve these kind of issues?

**Comment by lcc815** [comment]
thanks, I will study these issues you mentioned.
