### ISSUE TITLE
how to build uv index?

### ISSUE THREAD

**Issue by lcc815** [NVlabs/nvdiffrast#151]
Hi @s-laine,

I'm trying to use a texture map to optimize my mesh color. But I don't have an uv index, so I wonder how can I build one. I have tried [xatlas-python](https://github.com/mworchel/xatlas-python), but it will duplicates vertices. Could you give any advice to build an uv index?
Also, xatlas is so slow that it cannot be used for my mesh.
Thanks.

**Comment by s-laine** [comment]
Finding a good uv parameterization is a difficult task and still an open research problem, and I don't have any particular solution to recommend. Ideally, the uv parameterization is generated together with the mesh, but if this is not possible in your use case, using an atlas generator is probably the only option.
