### ISSUE TITLE
differentiable Texture uv

### ISSUE THREAD

**Issue by shi-yan** [NVlabs/nvdiffrast#155]
I want to use a differentiable render to automatically generate uv mapping

(generate texture coordinates).

I briefly read the paper, I have an impression that this can't be done using this library? because for each pixel, the forward pass needs to determine the corresponding triangle.

In my case, since I want to derive the uv coordinates, pixels can change their corresponding triangle. This is not differentiable, right? Am I right?

**Comment by s-laine** [comment]
I'm not quite sure I understand the question. Any attributes you use as inputs to `interpolate()` will receive gradients propagated from the gradients of the output. However, if you try to optimize both texture contents and uv coordinates simultaneously, it might be that the gradients don't point towards a good solution.

In any case, changing uv coordinates doesn't change which triangle a pixel lands on, so the index discontinuity should not be a problem.
