### ISSUE TITLE
Bogus error in even-channeled texture mapping

### ISSUE THREAD

**Issue by msqrt** [NVlabs/nvdiffrast#16]
Using pytorch, calling `dr.texture` for a texture with an even number of channels gives the error "tex or mip input tensor not aligned to float4" (or "float2" for 2 channels). To reproduce, replace line 34 in `samples/torch/earth.py` with the following (making the texture 4-channeled and discarding the last channel after texturing; should be perfectly OK):
```
        tex = torch.cat((tex, tex[...,:1]),-1)
        color = dr.texture(tex[None, ...], texc, texd, filter_mode='linear-mipmap-linear', max_mip_level=max_mip_level)[..., :3]
```

This seems to be due to [this](https://github.com/NVlabs/nvdiffrast/blob/5a2d5d595ef94c63f186dc497c6223c866a33995/nvdiffrast/torch/torch_texture.cpp#L322) and [this](https://github.com/NVlabs/nvdiffrast/blob/5a2d5d595ef94c63f186dc497c6223c866a33995/nvdiffrast/torch/torch_texture.cpp#L329) line in `torch_texture.cpp`, where the condition should probably read `i <= p.mipLevelMax` instead of `0 <= p.mipLevelMax`.

**Comment by s-laine** [comment]
Oof, fixed 😅. Thanks for the report!
