### ISSUE TITLE
Is it possible to run this on 3090GPU+pytorch1.7.1+tensorflof1.15.0+pytorch3d?

### ISSUE THREAD

**Issue by changfali** [NVlabs/nvdiffrast#161]
Hello,
I'm trying to run [this repository](https://github.com/csbhr/FFHQ-UV), which need the environment：
![C29qcAA52z](https://github.com/NVlabs/nvdiffrast/assets/68762767/a81fac29-5ef0-436c-8c7c-fbff2fb17cba)
But I only have a 3090GPU, is it possible to make it work?

**Comment by s-laine** [comment]
Based on the error message, it looks like you don't have Cuda properly installed. We unfortunately cannot provide personal tech support here for setting up the execution environment.

Closing as out of scope.
