### ISSUE TITLE
Cannot use with pyrender

### ISSUE THREAD

**Issue by agnJason** [NVlabs/nvdiffrast#169]
```
import pyrender
import nvdiffrast.torch as dr
glctx = dr.RasterizeGLContext()
```
raise segmentation fault

**Comment by s-laine** [comment]
Creating the OpenGL rasterizer context before importing pyrender may help.

Alternatively, consider using `RasterizeCudaContext` instead of `RasterizeGLContext`. The Cuda rasterizer does not use OpenGL at all, so there won't be a conflict with pyrender.

**Comment by agnJason** [comment]
Thanks. I got it!
