### ISSUE TITLE
depth image render

### ISSUE THREAD

**Issue by pysmeeatioj** [NVlabs/nvdiffrast#172]
Is there a way to render depth using nvdiffrast? And can it remain differentiable? What about the normal map?

**Comment by s-laine** [comment]
Yes, both are possible. For depth, compute per-vertex camera-space depths and use the `interpolate` op with that as a vertex attribute to get a differentiable depth map. Similarly, to render a normal buffer, construct per-vertex normal vectors in any space you like, and interpolate those to get a per-pixel result.

**Comment by pysmeeatioj** [comment]
> Yes, both are possible. For depth, compute per-vertex camera-space depths and use the `interpolate` op with that as a vertex attribute to get a differentiable depth map. Similarly, to render a normal buffer, construct per-vertex normal vectors in any space you like, and interpolate those to get a per-pixel result.

Thank you for your prompt reply! Are there any examples or tutorials for reference?

**Comment by s-laine** [comment]
A comment reply [here](https://github.com/NVlabs/nvdiffrast/issues/118#issuecomment-1666875029) appears to contain an example of interpolating a depth value, but I haven't tested if it works. For normal vectors, the solution is similar. See, e.g., [here](https://github.com/NVlabs/nvdiffrec/blob/e7f2181b8a60eb8fedcdb4ad4d05bff3c0cf9bc1/render/render.py#L155) for an example of normal buffer computation in a different project built on top of nvdiffrast.

**Comment by pysmeeatioj** [comment]
![image](https://github.com/NVlabs/nvdiffrast/assets/142431004/5c87d78a-0292-426b-9289-9b1ef2f3b0de)
![image](https://github.com/NVlabs/nvdiffrast/assets/142431004/68daa4ba-c308-4f3a-8bb5-41fb537e3a0e)
thinks, it works! I get normal map by the depth gradient. And it is differentiable.

**Comment by yuhaoliu7456** [comment]
> op of nvd

Can you share your code example for obtaining the normal map?
