### ISSUE TITLE
uv value range for the texture function

### ISSUE THREAD

**Issue by ruiqixu37** [NVlabs/nvdiffrast#187]
Hi, 

Thank you very much for the amazing library! I just want to check for the `nvdiffrast.torch.texture` function, are the values of `uv` expected to be [0, 1]? I know [0, 1] is the conventional value range, but I just want to confirm that as the doc does not specify.

**Comment by s-laine** [comment]
Yes, that's correct. I'll add this in the documentation in the next release.

**Comment by ruiqixu37** [comment]
Got it, appreciate your quick response!
