### ISSUE TITLE
Why is abs() not applied to area calculation?

### ISSUE THREAD

**Issue by takiyu** [NVlabs/nvdiffrast#19]
I have a question about backward of rasterization.

It seems that the code contains area calculation to obtain barycentric coordinate.
However there was no `abs()` function.
```
float a0 = p1x*p2y - p1y*p2x;
float a1 = p2x*p0y - p2y*p0x;
float a2 = p0x*p1y - p0y*p1x;
```
https://github.com/NVlabs/nvdiffrast/blob/main/nvdiffrast/common/rasterize.cu#L82

The case will not happen when 'a0', 'a1', and 'a2' are negative values?

**Comment by s-laine** [comment]
Sorry for the late reply &mdash; the unnormalized barycentrics, i.e., edge function evaluations, can indeed be negative. However, the sign cancels out when normalizing by area of triangle which would also be negative in this case. Thus it is simpler to consider all of these quantities as signed and avoid the `abs()`.
