### ISSUE TITLE
module 'open3d' has no attribute 'cuda'

### ISSUE THREAD

**Issue by Ssqjxxlwhy** [NVlabs/nvdiffrast#191]
Hi！there is a problem when I run my project：

D:\Anaconda\envs\Sherpa3D\lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "D:\Sherpa3D-main\train.py", line 801, in <module>
    init_shape.vertices = o3d.cuda.pybind.utility.Vector3dVector(vertices)
AttributeError: module 'open3d' has no attribute 'cuda'

Process finished with exit code 1

can anybody help me?

**Comment by s-laine** [comment]
This error does not seem to be related to nvdiffrast but Open3D. I suggest looking at [Open3D's issue tracker](https://github.com/isl-org/Open3D/issues). Closing as off-topic.
