### ISSUE TITLE
Can not install. Any Suggestion?

### ISSUE THREAD

**Issue by garrisonz** [NVlabs/nvdiffrast#203]
Thanks for your great work!
After successfullly install nvdiffrast, there no `nvdiffrast_plugin.so` or `nvdiffrast_plugin_gl.so` under .cache/torch_extensions folder. Any suggestion?

The log on terminal is following:

```
(nvdiffrast) :~/w/3drecon/nvdiffrast$ pip install .
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing /home/zhangyupeng/w/3drecon/nvdiffrast
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/zhangyupeng/miniconda3/envs/nvdiffrast/lib/python3.10/site-packages (from nvdiffrast==0.3.3) (2.1.2)
Building wheels for collected packages: nvdiffrast
  Building wheel for nvdiffrast (setup.py) ... done
  Created wheel for nvdiffrast: filename=nvdiffrast-0.3.3-py3-none-any.whl size=139907 sha256=09d25434757f49b1fe7e18503980f7a191a24ade9787f45187e065a19762b314
  Stored in directory: /tmp/pip-ephem-wheel-cache-q6hq6ibl/wheels/69/ed/bb/3d6d604e107585e06dd67d18880d4a26b1087731dcfe23e50d
Successfully built nvdiffrast
Installing collected packages: nvdiffrast
Successfully installed nvdiffrast-0.3.3
(nvdiffrast) :~/w/3drecon/nvdiffrast$
(nvdiffrast) :~/w/3drecon/nvdiffrast$
(nvdiffrast) :~/w/3drecon/nvdiffrast$ ls ~/.cache/torch_extensions/*/nvdiffrast*
/home/zhangyupeng/.cache/torch_extensions/py310_cu121/nvdiffrast_plugin:
build.ninja

/home/zhangyupeng/.cache/torch_extensions/py310_cu121/nvdiffrast_plugin_gl:
build.ninja
```

**Comment by garrisonz** [comment]
May I know how nvdiffrast compiles the c++ / cuda source code?

As I know, the source code of pytorch extension is compiled by the command similar with "ext_modules = [CppExtension('xxx',sources=['xxx.cpp'])]," in setup.py.
But, I don't find ext_module setup in nvdiffrast setup.py file.

Looking forward to your reply~

**Comment by s-laine** [comment]
The C++/Cuda plugin is compiled when the library is first used. The compilation code is in function `_get_plugin()` in `nvdiffrast/torch/ops.py` [here](https://github.com/NVlabs/nvdiffrast/blob/729261dc64c4241ea36efda84fbf532cc8b425b8/nvdiffrast/torch/ops.py#L20).

**Comment by garrisonz** [comment]
Thanks!
