### ISSUE TITLE
Rendering texture or vertex colours

### ISSUE THREAD

**Issue by mshooter** [NVlabs/nvdiffrast#205]
When I am setting the vertex colours not to (0,1,0) but to (0.5, 0.75, 0.1) the colours displayed on the rendered image are rounded up. Could anyone explain why this is? I have similar problem with textures (see image below).
I exported the texture from Blender. 

Original: 
![Screenshot from 2024-10-19 14-54-09](https://github.com/user-attachments/assets/76d3dd98-4fe2-4c0e-b837-2d0cf518bb02)

Rendered using nvdiffrast
![tri0](https://github.com/user-attachments/assets/e7877534-5498-41ef-afdd-e6e652786508)

**Comment by s-laine** [comment]
This looks like a problem with value ranges used to represent colors. My guess is that you're using colors in range [0, 255] when rendering but your image exporter expects a range of [0, 1] and clamps the pixel values to that.

**Comment by mshooter** [comment]
@s-laine Thank you, I was converting the ranges twice.
