### ISSUE TITLE
How can I install nvdiffrast in a centos env ?

### ISSUE THREAD

**Issue by ToTheBeginning** [NVlabs/nvdiffrast#28]
Thanks for sharing your amazing work.

Due to some restrictions, I can only build a docker image with centos. But from the dockerfile, I found some libs that are only available in ubuntu, and I am not sure how to modify the dockerfile to be compatible with centos.

Can you help me with this ?

**Comment by s-laine** [comment]
Sorry for the delayed answer. We have only run nvdiffrast under Ubuntu, and although I don't see why it wouldn't work under other distros with the right libraries and graphics drivers, we have no experience one way or another with CentOS. This unfortunately also means that we don't have suitable dockerfiles or suggestions to give.
