### ISSUE TITLE
error  run inside   WSL2 with cuda  and pytorch  

### ISSUE THREAD

**Issue by Jiakui** [NVlabs/nvdiffrast#29]
### **python3 pose.py**

No output directory specified, not saving log or images
Mesh has 12 triangles and 24 vertices.
[F glutil.cpp:338] eglInitialize() failed
Aborted

**Comment by s-laine** [comment]
It appears that EGL doesn't work in your environment. I don't know if it's even supposed to work in WSL &mdash; we have no experience with WSL and it's not one of the tested configurations, so unfortunately I don't have any advice to give here.
