### ISSUE TITLE
run  sample failed

### ISSUE THREAD

**Issue by ForrestPi** [NVlabs/nvdiffrast#41]
python cube.py --resolution 16 --display-interval 10 

got error

[F glutil.cpp:338] eglInitialize() failed
Aborted (core dumped)

I have installed  "apt-get install libegl1-mesa-dev"    and run the demo in linux server  with nvidia-gpu

**Comment by s-laine** [comment]
Have you tried running the sample in the provided Docker environment? EGL is tricky to set up correctly, so you should first try running in Docker. Assuming that works, you can then use the environment as a reference for manual setup.
