### ISSUE TITLE
nvidia driver version

### ISSUE THREAD

**Issue by haoxurt** [NVlabs/nvdiffrast#42]
Hi, I have ran the demo with nvidia driver 450.102.04. However, I failed when I used other environment with nvidia driver 450.80.02. Could you tell me your nvidia driver version?

**Comment by s-laine** [comment]
I seem to have 450.80.02 in our local cluster and it has been working fine.

**Comment by haoxurt** [comment]
I built a docker following Dockerfile and it occur the error `[F glutil.cpp:338] eglInitialize() failed`

**Comment by s-laine** [comment]
That is quite surprising, and I don't know how to help, as we don't see the issue in our end. Did you reboot after installing the driver? Did you build the Docker container with the same driver version installed as you had when running it? I don't know if that matters, but it might.

**Comment by nurpax** [comment]
I tried with driver version `460.91.03` using the latest code from this repo and the sample seems to work for me with the following commands:

```
bash ./run_sample.sh --build-container
bash ./run_sample.sh ./samples/torch/cube.py --resolution 32
```

Can confirm that the above still fails for you, even after a reboot of your machine?

Note that you need to let Docker use gpus with the `--gpus all` switch as is done in the `run_sample.sh` script.

If the problem persists, make sure that you can run some other GPU commands in your container, like `nvidia-smi`.

**Comment by haoxurt** [comment]
> That is quite surprising, and I don't know how to help, as we don't see the issue in our end. Did you reboot after installing the driver? Did you build the Docker container with the same driver version installed as you had when running it? I don't know if that matters, but it might.

I have not solved the problem, it coud be related to basic system environment of server
