### ISSUE TITLE
Centos support

### ISSUE THREAD

**Issue by jiaxiangshang** [NVlabs/nvdiffrast#48]
Hi all, really nice work and it is very convenient on ubuntu.
However, the online server always centos, will you update some support on centos?
Thanks.

**Comment by s-laine** [comment]
We don't currently have plans to support CentOS. But I didn't know there is an online service that uses only CentOS, can you tell me what it is?

**Comment by jiaxiangshang** [comment]
Oh sorry i didn't make it clear，it is our servers rather than the online server(like Colab). But, it is really difficult to make nvdiffrast work on centos, looking forward to your further supporting.

**Comment by s-laine** [comment]
This was touched previously in issue #28 and the situation has not changed. We have no experience with CentOS and haven't developed nvdiffrast with it in mind, so providing support could be a significant undertaking if there are missing packages, obsolete drivers, and so on.

As such, we do not expect to actively support CentOS for the time being. I can only suggest trying to find a way to get all the required dependencies installed in CentOS, and if after that nvdiffrast still refuses to run, then it might be a problem in the code itself and potentially worth looking into.

**Comment by jiaxiangshang** [comment]
Ok, thanks for your help.

**Comment by wuneng** [comment]
I have installed nvdiffrast on centos successfully.

**Comment by o0Helloworld0o** [comment]
Hi @wuneng ! Can you share the installation steps briefly? This is a great help for beginners. Thank you.

**Comment by XinYu-Andy** [comment]
> Hi @wuneng! If you have the time, could you please briefly outline the (non-trivial) steps that were needed to get it working?
> 
> It would be great to be able to point here in the documentation, so that others can benefit from your solution too.

Hi, have you solved this problem?
