### ISSUE TITLE
Runtime Error: glLinkProgram() failed

### ISSUE THREAD

**Issue by Mirocos** [NVlabs/nvdiffrast#50]
Hi, I tried to use nvdiffrast with the mentioned document in Windows 10.
When I executed following commad, runtime error happened:
```bash
D:\development\anaconda3\envs\dmodel\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File ".\samples\torch\cube.py", line 200, in <module>
    main()
  File ".\samples\torch\cube.py", line 191, in main
    mp4save_fn='progress.mp4'
  File ".\samples\torch\cube.py", line 76, in fit_cube
    glctx = dr.RasterizeGLContext()
  File "D:\development\anaconda3\envs\dmodel\lib\site-packages\nvdiffrast\torch\ops.py", line 151, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
RuntimeError: glLinkProgram() failed:
Fragment info
-------------
0(2) : error C7528: OpenGL reserves names starting with 'gl_'
(0) : error C2003: incompatible options for link
```

my PyOpenGL version is 3.1.5 and glfw version is 2.3.0.

**Comment by geek0075** [comment]
Hi,

I got the following exception trying to run:

$ python test.py --name=model1 --epoch=20 --img_folder=./datasets/mydata

Driver Provider: NVIDIA
Driver Version: 30.0.15.1179
Driver Date: 2/10/2022
Digital Signer: Microsoft Windows Hardware Compatibility Publisher

This returns an error:

Error C7528: OpenGL reserves names starting with 'gl_': gl_PrimitiveID
Error C2003: Incompatible options for Link

Has anyone else experienced this? I am running on Windows with NVIDIA GeForce 3090.

Kind Regards.

**Comment by geek0075** [comment]
@s-laine

**Comment by Xiaoming-Zhao** [comment]
Hi @s-laine, just a heads up here. I encounter a similar issue with GPU driver 515.43.04. Commenting out all `in int gl_` as you suggested fix it.

```bash
Traceback (most recent call last):
  File "test_gmpi.py", line 154, in <module>
    main(0, opt, opt.gmpi_img_root, opt.gmpi_depth_root, opt.gmpi_detect_root)
  File "test_gmpi.py", line 101, in main
    model.test()           # run inference
  File "/data1/xz23/gmpi/code/private_Deep3DFaceRecon_pytorch/models/base_model.py", line 162, in test
    self.forward()
  File "/data1/xz23/gmpi/code/private_Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 139, in forward
    self.pred_vertex, self.facemodel.face_buf, feat=self.pred_color)
  File "/home/xz23/Python/miniconda3/envs/deep3d_pytorch_new/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1/xz23/gmpi/code/private_Deep3DFaceRecon_pytorch/util/nvdiffrast.py", line 58, in forward
    self.glctx = dr.RasterizeGLContext(device=device)
  File "/home/xz23/Python/miniconda3/envs/deep3d_pytorch_new/lib/python3.6/site-packages/nvdiffrast/torch/ops.py", line 151, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
RuntimeError: glLinkProgram() failed:
Fragment info
-------------
0(2) : error C7528: OpenGL reserves names starting with 'gl_': gl_PrimitiveID
(0) : error C2003: incompatible options for link
```

**Comment by s-laine** [comment]
Hi @Xiaoming-Zhao, the current version shouldn't have any `int gl_` variables declared anymore. However, I apparently made the same mistake again with the A100 workaround having `in vec4 gl_FragCoord` and `out float gl_FragDepth` declarations. Was it these lines you had to remove? In any case, I'll delete them in the next release.

**Comment by PoopBear1** [comment]
Same question happends on version 515.65.01, even though I delete the declaration int gl_.

GLSL Shader compilation failed: <string>:
0(8) : error C7528: OpenGL reserves names starting with 'gl_': gl_PrimitiveID
0(11) : warning C7555: 'varying' is deprecated, use 'in/out' instead

**Comment by s-laine** [comment]
Currently nvdiffrast does not have any 'gl_' declarations in the shader code. Are you using an older version of nvdiffrast?

The GLSL compiler error doesn't make sense if there are no declarations for gl_ variables. Maybe the C++ plugin was not rebuilt for one reason or another? To be certain, see what `torch.utils.cpp_extension._get_build_directory('nvdiffrast_plugin', False)` says and delete that directory.

As a side note, the shader code has never included keyword 'varying', so I don't know what's up with the warning.
