### ISSUE TITLE
[F glutil.cpp:338] eglInitialize() failed

### ISSUE THREAD

**Issue by BianFeiHu** [NVlabs/nvdiffrast#58]
Thanks for this amazing tool.
i was using docker and  after execute ./run_sample.sh ./samples/torch/cube.py --resolution 32, i encounter this error
[F glutil.cpp:338] eglInitialize() failed
And my gpu is RTX3080
![image](https://user-images.githubusercontent.com/57490712/145060165-67ad0f2e-b155-470d-9934-22c520c901db.png)

**Comment by s-laine** [comment]
This has previously been a driver issue, see [here](https://github.com/NVlabs/nvdiffrast/issues/51#issuecomment-954275825) and [here](https://github.com/NVlabs/nvdiffrast/issues/56#issuecomment-985228197). Note that a reboot is probably required after installing the drivers ([#24](https://github.com/NVlabs/nvdiffrast/issues/24#issuecomment-824702760)).

**Comment by BianFeiHu** [comment]
Thanks a lot and this solution definitely solved my problem

**Comment by jby1993** [comment]
@BianFeiHu Hi, I have met the same problem. In my host environment, I can use nvdiffrast normally. But in docker, this error happens. I want to know how you solved this problem? Did you reinstall the driver?

**Comment by BianFeiHu** [comment]
@jby1993 Yes, I reinstalled the driver with OpenGL.

**Comment by FarisHijazi** [comment]
I fixed it simply with replacing `dr.RasterizeCudaContext` with `dr.RasterizeCudaContext`

I was using the `nvdiffrec` repo

**Comment by Walterkd** [comment]
> 

which file should I edit? "replacing dr.RasterizeGLContext with dr.RasterizeCudaContext"

**Comment by YuQiao0303** [comment]
> > 
> 
> which file should I edit? "replacing dr.RasterizeGLContext with dr.RasterizeCudaContext"

You can search your code for 'RasterizeGLContext ' if possible, and you may see something like 'dr.RasterizeGLContext' where 'dr' was 'import nvdiffrast.torch as dr'

**Comment by Larerr** [comment]
> I fixed it simply with replacing `dr.RasterizeGLContext` with `dr.RasterizeCudaContext`
> 
> I was using the `nvdiffrec` repo

niubi!

**Comment by gameveloster** [comment]
I'm getting the same error in a Docker container based on `pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime`, but not in the host.

The installed version of `nvdiffrast` is on the Jun 30 2023 commit c5caf7bdb8a2448acc491a9faa47753972edd380

Anyone knows how to fix this error `[F glutil.cpp:338] eglInitialize() failed` when running from inside the Docker container?

@jby1993 @BianFeiHu How did you install the nvidia driver with OpenGL in the docker container? How did you restart the container?

@Larerr @FarisHijazi

**Comment by s-laine** [comment]
@gameveloster Have you checked the example Docker setup [here](https://github.com/NVlabs/nvdiffrast/tree/main/docker)? It's a little out of date, but includes non-obvious steps that were necessary to make EGL available in the container.

Of course, things may have changed so that the required setup is now different. In that case I don't have an answer for you, unfortunately.

**Comment by Lxiangyue** [comment]
> I fixed it simply with replacing `dr.RasterizeGLContext` with `dr.RasterizeCudaContext`
> 
> I was using the `nvdiffrec` repo

thanks so much!!!❤️

**Comment by Moondok** [comment]
> I fixed it simply with replacing `dr.RasterizeGLContext` with `dr.RasterizeCudaContext`
> 
> I was using the `nvdiffrec` repo

Thanks! It works .
