### ISSUE TITLE
question about antialias

### ISSUE THREAD

**Issue by l1346792580123** [NVlabs/nvdiffrast#69]
It seems that antialias operation is used to get correct gradient when generating silhouette. My question is should I need to use antialias operation for attribute interpolation map? I use CookTorrance rendering model, and the properties of vertices such as diffuse, specular need to be interpolated. Should I add antialias operation after interpolate?

**Comment by s-laine** [comment]
You should antialias the final pixel colors, but *not* any of the intermediate buffers containing interpolated attributes, texture coordinates, and so on.

Antialiasing these intermediate buffers would produce values that don't correspond to any surface point. For example, antialiasing texture coordinates would blend them towards zero at the silhouette, which makes no sense. The same applies to the inputs or intermediate values of any shading setup, including the Cook-Torrance model.

**Comment by l1346792580123** [comment]
Thanks for you explanation.

**Comment by l1346792580123** [comment]
> You should antialias the final pixel colors, but _not_ any of the intermediate buffers containing interpolated attributes, texture coordinates, and so on.
> 
> Antialiasing these intermediate buffers would produce values that don't correspond to any surface point. For example, antialiasing texture coordinates would blend them towards zero at the silhouette, which makes no sense. The same applies to the inputs or intermediate values of any shading setup, including the Cook-Torrance model.

Sorry for opening this issue again. Due to the limitation of GPU memory, my actual behavior is to take out the valid interpolated attributes to calculate BRDF and final color according to the result of rasterize (rast_out[:,:,:,3] > 0). And I put the color value back to the image according to the index to get the final result. The other value in the final result is initialized to zero manually. Finally, I perform antialias on the final result.  Is the pipeline correct?

**Comment by s-laine** [comment]
I'm not sure I completely understand your pipeline, but if the antialiasing is performed on an image where all shading has been done, it should be correct.

**Comment by l1346792580123** [comment]
> I'm not sure I completely understand your pipeline, but if the antialiasing is performed on an image where all shading has been done, it should be correct.

I interpolate the attributes of points to get the attribute map. Then I  take out the valid attributes according to rast_out[:,:,:,3] > 0 and compute the final color. The shading only has been done on part of the image.

**Comment by s-laine** [comment]
This sounds perfectly fine. As long as you reconstruct the image by putting the shading results into the same pixel indices where the attributes came from, you can do the antialiasing operation on this image.

**Comment by l1346792580123** [comment]
Thanks for your answer! I put the shading results back according to indices and the other pixel values is set to zero.
