### ISSUE TITLE
why I always meet No module named 'nvdiffrast.torch'; 'nvdiffrast' is not a package

### ISSUE THREAD

**Issue by ZhenyanSun** [NVlabs/nvdiffrast#74]
I can run the samples successfully

**Comment by s-laine** [comment]
Sounds like you haven't installed nvdiffrast with pip, and you don't have the correct directory in `PYTHONPATH` environment variable.

**Comment by s-laine** [comment]
I cannot even guess what might be wrong without further information. I suggest you compare what you're doing with the example code. Perhaps you could modify an example bit by bit into the direction you want to go, so that you can see where things break down.

**Comment by VIROBO-15** [comment]
@ZhenyanSun where you were able to resolve the issue

**Comment by mkat2** [comment]
working option is: git clone https://github.com/NVlabs/nvdiffrast and then from that directory pip install . (dont forget the dot)
