### ISSUE TITLE
ImportError: generic_type: type "RasterizeGLStateWrapper" is already registered!

### ISSUE THREAD

**Issue by jiaxiangshang** [NVlabs/nvdiffrast#79]
Hi, groupers

I meet this error when I try to sample a texture map by the uv.
`out = dr.texture(self.data, texc, texc_deriv, filter_mode=filter_mode)
`

The error is
`ImportError: generic_type: type "RasterizeGLStateWrapper" is already registered! `

Best

**Comment by s-laine** [comment]
Hi, does this happen when running one of our examples without modifications? Which one?

**Comment by jiaxiangshang** [comment]
Oh, yes, it is super clear for me, and the problem is solved.

Thank you very much.
