### ISSUE TITLE
Docker image build broken by GPG key rotation

### ISSUE THREAD

**Issue by jdagdelen** [NVlabs/nvdiffrast#80]
Tried building the Docker image on Linux and ran into [Public GPG key error](https://github.com/NVIDIA/nvidia-docker/issues/1631 ) 

Adding the following to top of Dockerfile seems to have solved it.

```
RUN rm /etc/apt/sources.list.d/cuda.list
RUN rm /etc/apt/sources.list.d/nvidia-ml.list
RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
```

**Comment by s-laine** [comment]
Thank you for the report. Can you confirm if this is still an issue? We haven't been able to reproduce it ourselves, and we're thinking it may have been some sort of intermittent failure. Our containers should be available without authentication, and if not, we're going to have problems with all our other projects too.
