### ISSUE TITLE
Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]

### ISSUE THREAD

**Issue by JasonLSC** [NVlabs/nvdiffrast#87]
Hi, I come across an error
`Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]`
Maybe it is related to my OpenGL environment?

**Comment by s-laine** [comment]
Most likely. Are you using the supplied Docker environment?

**Comment by JasonLSC** [comment]
Not yet. Maybe I will try the Docker environment later.

**Comment by s-laine** [comment]
If you continue to have OpenGL problems, you can now try the CUDA-based rasterizer included in v0.3.0. Closing.
