### ISSUE TITLE
Wireframe figures in paper & docs

### ISSUE THREAD

**Issue by yoterel** [NVlabs/nvdiffrast#97]
Hi,
Were the wire-frame (super-imposed) figures in the documentation rendered using nvdiffrast?
Is it possible to share the material model used to yield those?

Thanks

**Comment by s-laine** [comment]
No, those were rendered in a separate visualizer that used OpenGL only. The wireframe was rendered on top of textured mesh using `glPolygonMode(GL_FRONT_AND_BACK, GL_LINE)` and a small geometry offset towards viewer in z direction.

**Comment by mhubii** [comment]
Might post a code snippet soon. For anyone stumbling across this, the barycentric coordinates that are returned by the rasterize operation can be used nicely for rendering a wireframe.
